### ISSUE TITLE
Question/Feature Alternative Base(Context) Path

### ISSUE THREAD

**Issue by muratkarakas** [archerysec/archerysec#345]
**Is your feature request related to a problem? Please describe.**
By default application runs in "/" context path. When using kubernetes ingress or reverse proxy I need to access application  with a path "/archerysec" for proper navigation. Is there way to achieve this. Currently application tries to load all static files from ROOT which  fails when using path other then "/" in proxy

**Describe the solution you'd like**
config file or run flag( via ENV var) pass alternative application path

Thanks

**Comment by anandtiwarics** [comment]
have you tried with Nginx proxy?

**Comment by muratkarakas** [comment]
No I tried to use it with k8s ingress (traefik). You can find ingress config below. Problem is I have to set path for for my ingress load balancer(Each application has different paths,domain and subdomain is same )


```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: secops-webscanners
  namespace: secops
  annotations:
    traefik.frontend.rule.type: PathPrefix // removes  "/archerysec " path when sending request  backend
spec:
  rules:
  - http:
      paths:
      - path: /archerysec //  proxy path to access backend archerysec service
        backend:
          serviceName: archerysec  // kuberenetes service listening on port name named "http"
          servicePort: http 
```
With this setup I can access the application with

subdomain.domain:port/archerysec but it  redirects to login path   like  subdomain.domain:port/login (and fails). If I could set   "/archerysec" as conext path I think it would work.

In secod case I tried, I change ingress path to "/webscanners" then I can access to login page page with subdomain.domain:port/webscanners/login but this time static files failed to load because it tries to load from subdomain.domain:port/static/** which is not valid.

As a result is it possible to  access to application over any proxy(ngix...) with custom proxy path like
http:myproxyaddress:8080/customerpathforarcherysec
