### ISSUE TITLE
ProgrammingError at /webscanners/auth/, relation "auth_user" does not exist 

### ISSUE THREAD

**Issue by r3mattia** [archerysec/archerysec#451]
**Describe the bug**
I have created a Helm chart to deploy ArcherySec with:
- OpenVAS
- Arachni
- OWASP Zap

included in the same Helm chart.

My Helm values file looks as follows:

```
global:
  name: devsecops-tools
  namespace: default
  arachniEnabled: true
  clairEnabled: false
  openvasEnabled: true
  zapEnabled: true

arachni:
  deployment:
    applicationName: arachni-application
    applicationLabel: arachni-app
    containerPort: 7331
    deploymentName: arachni-deployment
    dockerImageName: ahannigan/docker-arachni
    replicas: 1
    resources:
      memoryLimit: 2000Mi
      memoryRequest: 1024Mi
  service:
    serviceLabel: arachni-service
    type: ClusterIP

archerysec:
  dbDeployment:
    applicationLabel: archerysec-postgres
    containerPort: 5432
    dockerImageName: postgres:10.1-alpine
    deploymentName: archerysec-postgres-deployment
    replicas: 1
  dbService:
    type: ClusterIP
    serviceLabel: db-service
  deployment:
    applicationLabel: archerysec-app
    applicationName: archerysec-application
    containerPort: 8000
    deploymentName: archerysec-deployment
    dockerImageName: archerysec/archerysec
    replicas: 1
  service:
    nodePort: 30008
    type: NodePort 

openvas:
  deployment:
    applicationLabel: openvas-app
    applicationName: openvas-application 
    containerName: openvas
    containerPort: 9390
    deploymentName: openvas-deployment
    dockerImageName: avhost/docker-openvas
    resources:
      memoryLimit: 1000Mi
      memoryRequest: 500Mi
    replicas: 1
  service:
    serviceLabel: openvas-service
    type: ClusterIP

zap:
  deployment:
    applicationName: zap-application
    applicationLabel: zap-app
    containerPort: 8090
    deploymentName: zap-deployment
    dockerImageName: owasp/zap2docker-stable
    replicas: 1
  service:
    serviceLabel: zaproxy
    type: ClusterIP

```

When I deploy this into a private AKS cluster I am able to access the GUI on the endpoint IP associated with the NodePort Kubernetes service.

However, when I login, I get a rather nasty looking error with the following details:

```

Request Method: | POST
-- | --
http://<PRIVATE_IP>/webscanners/auth/
3.1.5
ProgrammingError
relation "auth_user" does not exist LINE 1: ...user"."is_active", "auth_user"."date_joined" FROM "auth_user...                                                              ^
/home/archerysec/app/venv/lib/python3.6/site-packages/django/db/backends/utils.py, line 84, in _execute
/home/archerysec/app/venv/bin/python3
3.6.9
['/home/archerysec/app',  '/home/archerysec/app/venv/bin',  '/home/archerysec/app/venv/lib/python36.zip',  '/home/archerysec/app/venv/lib/python3.6',  '/home/archerysec/app/venv/lib/python3.6/lib-dynload',  '/usr/lib/python3.6',  '/home/archerysec/app/venv/lib/python3.6/site-packages',  '/home/archerysec/app/venv/lib/python3.6/site-packages/odf',  '/home/archerysec/app/venv/lib/python3.6/site-packages/odf',  '/home/archerysec/app/venv/lib/python3.6/site-packages/odf',  '/home/archerysec/app/venv/lib/python3.6/site-packages/odf',  '/home/archerysec/app/venv/lib/python3.6/site-packages/odf',  '/home/archerysec/app/venv/lib/python3.6/site-packages/odf',  '/home/archerysec/app/venv/lib/python3.6/site-packages/odf']
Mon, 22 Feb 2021 17:57:00 +0000

```

**To Reproduce**
1. Create a Helm chart with Values as mine.
2. Deploy into private AKS cluster
3. Access GUI on private IP of AKS cluster
4. Login with default credentials for archerysec

**Expected behavior**
I should be successfully logged in and see the homepage / dashboard post-login.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome
 - Version latest as per today

**Additional context**
It should be noted that I am injecting the PSQL credentials and DJANGO configuration as HashiCorp Vault secrets and sourcing these as `ENV`s thereafter. This means I use the following the following container commands in my `.yaml` deployment manifest:

For the POSTGRES deployment:
```
command:
  - sh
  - -c
  - . /vault/secrets/credentials && ./usr/local/bin/docker-entrypoint.sh postgres
```

For ARCHERYSEC deployment:
```
command:
   - sh
   - -c
   - . /vault/secrets/credentials && . venv/bin/activate && gunicorn -b 0.0.0.0:8000 archerysecurity.wsgi:application --workers=1 --threads=10 --timeout=1800
```
