### ISSUE TITLE
docker-compose fails becase of missing avhost/docker-openvas image

### ISSUE THREAD

**Issue by carldavis** [archerysec/archerysec#516]
`docker-compose up` fails because of a missing dependency.

1. `git clone https://github.com/archerysec/archerysec.git`
2. `docker-compose up -d`

`Error response from daemon: pull access denied for avhost/docker-openvas, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

Checking https://hub.docker.com/r/avhost/docker-openvas/ returns 404

**Comment by abejads** [comment]
got same issue

**Comment by mjtechguy** [comment]
I tried to track down the original repo to build from the Dockerfile and built it myself, but didn't have any luck.

I tried this repo and it appears to be actively maintained and a drop in replacement: https://hub.docker.com/r/immauss/openvas

Still doing testing. Use at your own risk.

**Comment by schniggie** [comment]
@mjtechguy have you successfully conntected this docker image as connector?

I tried the following config:

```
  openvas:
    image: immauss/openvas
    environment:
      - "PASSWORD=admin"
      - "USERNAME=admin"
      - "GMP=9390"    # to enable see docs
      - "HTTPS=false"  # wether to use HTTPS or not
    ports:
      - "9390:9390"
      - "9392:9392"
    expose:
      - "9390"
      - "9392"
    links:
      - archerysec
    container_name: openvas
```

Also tested with `"HTTPS=true"` but no luck at all. Connector always stays at not connected.
